@push('stylesheets')
    @vite('resources/css/comments.scss')
@endpush
@push('scripts')
    @vite('resources/js/comments.js')
@endpush
<div class="comments">        
    <span class="fa-stack">
        <i class="fa-solid fa-circle fa-stack-2x"></i>
        <i class="fa-solid fa-xmark fa-stack-1x"></i>
    </span>
    <h3>Comments</h3>
    top comments<br/>
    comments AJAXed<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    comments<br/>
    bottom
</div>